### ISSUE TITLE
Show some benchmarks against Mac::PropertyList

### ISSUE THREAD

**Issue by kulp** [kulp/Mac-PropertyList-SAX#7]
It has been years since `Mac::PropertyList::SAX` has been known (at least to @kulp) to be faster than `Mac::PropertyList`, for which it is meant to be a drop-in replacement. Prove that there is any use for the `::SAX` version at all.

**Comment by briandfoy** [comment]
I'm sure that any SAX parser will be faster. And, if we keep the interfaces the same, I can optionally use Mac::PropertyList::SAX if it is available.

**Comment by kulp** [comment]
> And, if we keep the interfaces the same, I can optionally use Mac::PropertyList::SAX if it is available.

That is kind of you to offer, @briandfoy. I have no interest in diverging the interfaces; since your module has had `create_from` (for some time now) I expect to deprecate my old `create_from_ref`, which had made my API a superset of yours.

I do wonder how often XML plists end up being used any more. If binary and JSON plists are much more common now, then `Mac::PropertyList::SAX` might not get used very much, so speed might be less relevant. It is conceivable that converting large binary plists to XML and using `::SAX` or `::XS` might be fast enough; hopefully a benchmark will show.

I plan to release an updated `Mac::PropertyList::SAX` within a week or so (and a new [`Mac::PropertyList::XS`][xs] in the weeks after that). If you see anything that would make it easier to delegate to `::SAX`, let me know any time.

[xs]: https://github.com/kulp/Mac-PropertyList-XS

**Comment by kulp** [comment]
Some very informal testing in Bash on my M1 Macbook reveals big variations in the speedup (between 10x and 100x for large files), correlated with file size but also with some unquantified kind of "complexity" (possibly nesting depth or types of elements).

- [x] I will review these raw data points more carefully later.

The presence of `Couldn't read anything!` for one of the plists is due to newly-filed https://github.com/llvm/llvm-project/issues/56380.

- [x] I will look for cleaner files later.

```bash
# On kulp's machine, these files are arranged smallest to largest (1236 bytes
# up to 2129278 bytes).
plists=(
    $HOME/tmp/llvm-project/lldb/test/API/macosx/find-dsym/deep-bundle/Info.plist
    /private/etc/openldap/AppleOpenLDAP.plist
    $HOME/tmp/llvm-project/clang/test/Analysis/Inputs/expected-plists/retain-release.m.objcpp.plist
    /private/var/db/SystemPolicyConfiguration/LegacyEntitlementAllowlist.plist
)

exec 2>&1 # Capture output from "time".

for p in "${plists[@]}"
do
    bytes=$(stat -f %z "$p")
    echo "Parsing $p ($bytes bytes) ..."
    for mod in Mac::PropertyList Mac::PropertyList::SAX
    do
        echo "... with $mod:"
        time perl -Mlib=lib -M$mod=parse_plist_file -e 'parse_plist_file(@ARGV)' $p
    done
done

```

<details>

```
Parsing /Users/kulp/tmp/llvm-project/lldb/test/API/macosx/find-dsym/deep-bundle/Info.plist (1236 bytes) ...
... with Mac::PropertyList:

real	0m0.045s
user	0m0.031s
sys	0m0.007s
... with Mac::PropertyList::SAX:
could not find ParserDetails.ini in /Users/kulp/perl5/lib/perl5/XML/SAX

real	0m0.041s
user	0m0.028s
sys	0m0.007s
Parsing /private/etc/openldap/AppleOpenLDAP.plist (116915 bytes) ...
... with Mac::PropertyList:

real	0m0.371s
user	0m0.362s
sys	0m0.007s
... with Mac::PropertyList::SAX:
could not find ParserDetails.ini in /Users/kulp/perl5/lib/perl5/XML/SAX

real	0m0.068s
user	0m0.059s
sys	0m0.006s
Parsing /Users/kulp/tmp/llvm-project/clang/test/Analysis/Inputs/expected-plists/retain-release.m.objcpp.plist (833576 bytes) ...
... with Mac::PropertyList:
Couldn't read anything! at -e line 1.

real	0m35.901s
user	0m35.278s
sys	0m0.487s
... with Mac::PropertyList::SAX:
could not find ParserDetails.ini in /Users/kulp/perl5/lib/perl5/XML/SAX

real	0m0.337s
user	0m0.315s
sys	0m0.012s
Parsing /private/var/db/SystemPolicyConfiguration/LegacyEntitlementAllowlist.plist (2129278 bytes) ...
... with Mac::PropertyList:

real	0m6.041s
user	0m3.888s
sys	0m2.147s
... with Mac::PropertyList::SAX:
could not find ParserDetails.ini in /Users/kulp/perl5/lib/perl5/XML/SAX

real	0m0.533s
user	0m0.518s
sys	0m0.012s
```

</details>

**Comment by kulp** [comment]
I somewhat improved the state of the art in #9, which I will consider to have completed benchmarking sufficiently for the v1.000 milestone.
